# Generated by Django 5.1.1 on 2024-09-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(blank=True, default='', max_length=60)),
                ('campus_state', models.CharField(blank=True, default=0, max_length=2)),
                ('campus_id', models.IntegerField(blank=True, default='', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'University Campus',
            },
        ),
    ]
