# Generated by Django 5.1.1 on 2024-09-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityname',
            name='campus_id',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
