# Generated by Django 5.1.1 on 2024-09-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0002_alter_universityname_campus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityname',
            name='campus_id',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='universityname',
            name='campus_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='universityname',
            name='campus_state',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
